# Generated by Django 4.0 on 2022-11-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeOffice',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.user')),
            ],
            bases=('MigrationApp.user',),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.user')),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist')),
            ],
            bases=('MigrationApp.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.user')),
                ('bilkent_id', models.CharField(default='', max_length=10, unique=True)),
                ('department', models.CharField(default='', max_length=10)),
            ],
            bases=('MigrationApp.user',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentCoordinator',
            fields=[
                ('management_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.management')),
                ('department', models.CharField(default='', max_length=10)),
            ],
            bases=('MigrationApp.management',),
        ),
        migrations.CreateModel(
            name='ExchangeCoordinator',
            fields=[
                ('management_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.management')),
            ],
            bases=('MigrationApp.management',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('management_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.management')),
                ('department', models.CharField(default='', max_length=10)),
            ],
            bases=('MigrationApp.management',),
        ),
        migrations.CreateModel(
            name='FormerStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.student')),
                ('begin_date', models.DateField(default='', max_length='20')),
                ('end_date', models.DateField(default='', max_length='20')),
                ('checkList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist')),
                ('uni_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.university')),
            ],
            bases=('MigrationApp.student',),
        ),
        migrations.CreateModel(
            name='ApplyingStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MigrationApp.student')),
                ('check_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist')),
            ],
            bases=('MigrationApp.student',),
        ),
    ]
