# Generated by Django 4.0 on 2022-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usera'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
