# Generated by Django 4.0 on 2022-11-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0002_alter_university_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.RemoveField(
            model_name='formerstudent',
            name='checkList',
        ),
        migrations.AlterField(
            model_name='applyingstudent',
            name='check_list',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist'),
        ),
        migrations.AlterField(
            model_name='management',
            name='check_list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist'),
        ),
    ]
