# Generated by Django 4.0 on 2022-11-20 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0003_alter_user_options_remove_formerstudent_checklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='MigrationApp.user')),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='MigrationApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'TODO List'},
        ),
        migrations.AddField(
            model_name='management',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='notification',
            name='banner',
            field=models.ImageField(blank=True, default=None, upload_to='noti_banners', verbose_name='a small image about the notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receive_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pictures'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_count', models.IntegerField(blank=True, default=0)),
                ('solved', models.BooleanField(default=False)),
                ('context', models.CharField(blank=True, default='', max_length=30)),
                ('start_date', models.DateTimeField(auto_now_add=True, max_length=40)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, max_length=40)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, max_length=40)),
                ('context', models.CharField(blank=True, default='', max_length=30)),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.management')),
            ],
        ),
    ]
