# Generated by Django 4.0 on 2022-11-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0004_chat_forum_alter_todolist_options_management_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingstudent',
            name='check_list',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist'),
        ),
    ]
