# Generated by Django 4.0 on 2022-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0006_alter_applyingstudent_check_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
