# Generated by Django 4.0 on 2022-11-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0007_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.FloatField(default=0, verbose_name='Erasmus grade points out of 100'),
        ),
        migrations.AlterField(
            model_name='management',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.todolist'),
        ),
    ]
