# Generated by Django 4.0 on 2022-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0009_course_alter_user_options_instructor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='question',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
