# Generated by Django 4.0 on 2022-12-07 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0010_thread_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='thread',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='contact',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=40),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(default='city, country', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='reviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taughtInEnglishInfo', models.CharField(blank=True, max_length=150)),
                ('quota', models.IntegerField(default=0)),
                ('university', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=500)),
                ('rating', models.FloatField(default=0)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.user')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=40)),
                ('thread', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.user')),
            ],
        ),
    ]
