# Generated by Django 4.0 on 2022-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0013_alter_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='header',
            field=models.CharField(default='', max_length=50),
        ),
    ]
