# Generated by Django 4.0 on 2022-12-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0014_thread_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['start_date']},
        ),
    ]
