# Generated by Django 4.0 on 2022-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0016_alter_reply_options_alter_thread_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default=1, max_length=10),
        ),
    ]
