# Generated by Django 4.0 on 2022-12-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0017_alter_thread_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='coordinator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='MigrationApp.departmentcoordinator'),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='languageRequirements',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='taughtInEnglishInfo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
