# Generated by Django 4.0 on 2022-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0020_alter_universitydepartment_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydepartment',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default=1, max_length=10),
        ),
    ]
