# Generated by Django 4.0 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0021_universitydepartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='deadline',
        ),
    ]
