# Generated by Django 4.0 on 2022-12-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0022_remove_university_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydepartment',
            old_name='languageRequirements',
            new_name='language_requirements',
        ),
        migrations.RenameField(
            model_name='universitydepartment',
            old_name='taughtInEnglishInfo',
            new_name='taught_in_english_info',
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='university',
            name='websiteLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='formerstudent',
            name='uni_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='former_students', to='MigrationApp.universitydepartment'),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default='CS', max_length=10),
        ),
    ]
