# Generated by Django 4.0 on 2022-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0023_rename_languagerequirements_universitydepartment_language_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydepartment',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
