# Generated by Django 4.0 on 2022-12-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0024_universitydepartment_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='websiteLink',
            new_name='website_link',
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='university',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='MigrationApp.university'),
        ),
    ]
