# Generated by Django 4.0 on 2022-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('studentId', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=80)),
                ('image', models.ImageField(upload_to='testApp/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
