# Generated by Django 4.0 on 2022-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_rename_studentid_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
