# Generated by Django 4.0 on 2022-11-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyingStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.student')),
                ('points', models.FloatField(help_text='Erasmus points of the student')),
            ],
            bases=('testApp.student',),
        ),
    ]
