# Generated by Django 4.0 on 2022-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_university_formerstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
