# Generated by Django 4.0 on 2022-12-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_university_department_university_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
