const HasatPhoneIP = "http://172.20.10.8:1000";
const HasatHomeIP = "http://192.168.1.40:1000";
const local = "http://127.0.0.1:8000";

//BASE
const BASE_URL = local;
const API_BASE_URL = `${BASE_URL}/api/`;
//UNI INFO
const API_UNIS_INFO_ENDPOINT = `${API_BASE_URL}all-unis/`;
const API_UNI_REVIEWS_ENDPOINT = `${API_BASE_URL}university/`;
//ANNOUNCEMENTS
const API_ANNOUNCEMENTS_ENDPOINT = `${API_BASE_URL}announcements/`;
const API_MAKE_ANNOUNCEMENT_ENDPOINT = `${API_ANNOUNCEMENTS_ENDPOINT}make-announcement/`;
//FORUM
const API_FORUM_ENDPOINT = `${API_BASE_URL}forum/`;
const API_ASK_QUESTION_ENPOINT = `${API_FORUM_ENDPOINT}home/ask-question/`;
//PROFILE
const API_LOGIN_ENDPOINT = `${API_BASE_URL}login/`;
const API_MYPROFILE_ENDPOINT = `${API_BASE_URL}my-profile/`;
const API_LOGOUT_ENDPOINT = `${API_BASE_URL}logout/`;
const API_PROFILE_ENDPOINT = `${API_BASE_URL}profile/`;
//ALL USERS
const API_ALL_USERS = `${API_BASE_URL}all-users/`;
const API_ALL_FORMER_STUDENTS_ENDPOINT = `${API_BASE_URL}all-former-students/`;
const API_ALL_APPLYING_STUDENTS_ENDPOINT = `${API_BASE_URL}all-applying-students/`;

//FILES
const API_FILES_ENDPOINT = `${API_BASE_URL}upload-file/`;
const API_DOWNLOAD_FILES_ENDPOINT = `${API_BASE_URL}download-file/`;
const API_EXCEL_ENDPOINT = `${API_BASE_URL}upload-excel/`;
const API_PRE_APPROVAL_ENDPOINT =`${API_BASE_URL}pdffile/`;

module.exports = {
  BASE_URL,
  API_BASE_URL,
  API_UNIS_INFO_ENDPOINT,
  API_ANNOUNCEMENTS_ENDPOINT,
  API_FORUM_ENDPOINT,
  API_ALL_APPLYING_STUDENTS_ENDPOINT,
  API_LOGIN_ENDPOINT,
  API_MYPROFILE_ENDPOINT,
  API_LOGOUT_ENDPOINT,
  API_ALL_USERS,
  API_PROFILE_ENDPOINT,
  API_UNI_REVIEWS_ENDPOINT,
  API_MAKE_ANNOUNCEMENT_ENDPOINT,
  API_ASK_QUESTION_ENPOINT,
  API_ALL_FORMER_STUDENTS_ENDPOINT,
  API_FILES_ENDPOINT,
  API_DOWNLOAD_FILES_ENDPOINT,
  API_EXCEL_ENDPOINT,
  API_PRE_APPROVAL_ENDPOINT,
};
