const HasatPhoneIP = "http://172.20.10.8:1000";
const HasatHomeIP = "http://192.168.1.40:1000";

const BASE_URL = HasatPhoneIP;
const API_BASE_URL = `${BASE_URL}/api/`;
const API_UNIS_INFO_ENDPOINT = `${API_BASE_URL}all-unis/`;
const API_ANNOUNCEMENTS_ENDPOINT = `${API_BASE_URL}announcements/`;
const API_FORUM_ENDPOINT = `${API_BASE_URL}forum/`;
const API_LOGIN_ENDPOINT = `${API_BASE_URL}login/`;
const API_ALL_APPLYING_STUDENTS_ENDPOINT = `${API_BASE_URL}all-applying-students/`;
const API_MYPROFILE_STUDENT_ENDPOINT = `${API_BASE_URL}my-profile/student/`;
const API_LOGOUT_ENDPOINT = `${API_BASE_URL}logout/`;
const API_ALL_USERS = `${API_BASE_URL}all-users/`;
const API_PROFILE_ENDPOINT = `${API_BASE_URL}profile/`;

module.exports = {
  BASE_URL,
  API_BASE_URL,
  API_UNIS_INFO_ENDPOINT,
  API_ANNOUNCEMENTS_ENDPOINT,
  API_FORUM_ENDPOINT,
  API_ALL_APPLYING_STUDENTS_ENDPOINT,
  API_LOGIN_ENDPOINT,
  API_MYPROFILE_STUDENT_ENDPOINT,
  API_LOGOUT_ENDPOINT,
  API_ALL_USERS,
  API_PROFILE_ENDPOINT,
  
};
