# Generated by Django 4.0 on 2022-12-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbint', '0009_document_applyingstudent_universityplaced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('studentID', models.CharField(default='', max_length=10)),
                ('faculty', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('transcriptPoints', models.CharField(default=0.0, max_length=10)),
                ('totalPoints', models.CharField(default=0.0, max_length=10)),
                ('duration', models.CharField(default='', max_length=100)),
                ('firstPrefUni', models.CharField(default='', max_length=100)),
                ('secondPrefUni', models.CharField(default='', max_length=100)),
                ('thirdPrefUni', models.CharField(default='', max_length=100)),
                ('fourthPrefUni', models.CharField(default='', max_length=100)),
                ('fifthPrefUni', models.CharField(default='', max_length=100)),
                ('placedUni', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbint.university')),
            ],
            options={
                'ordering': ['-totalPoints', '-transcriptPoints'],
            },
        ),
    ]
