# Generated by Django 4.1.3 on 2022-12-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileAnalyzeApp', '0003_rename_lastname_excelstudents_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelstudents',
            options={'ordering': ['-totalPoints', '-transcriptPoints']},
        ),
    ]
