# Generated by Django 4.1.3 on 2022-12-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MigrationApp', '0023_alter_universitydepartment_university'),
        ('FileAnalyzeApp', '0004_alter_excelstudents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelstudents',
            name='placedUni',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MigrationApp.university'),
        ),
    ]
