# Generated by Django 4.1.3 on 2022-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileAnalyzeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelstudents',
            name='studentID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
