# Generated by Django 4.0 on 2022-12-14 18:11

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyingstudent',
            options={'verbose_name': 'Applying Student', 'verbose_name_plural': 'Applying Students'},
        ),
        migrations.AlterModelOptions(
            name='departmentcoordinator',
            options={'verbose_name': 'Department Coordinator', 'verbose_name_plural': 'Department Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='exchangecoordinator',
            options={'verbose_name': 'Exchange Coordinator', 'verbose_name_plural': 'Exchange Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='formerstudent',
            options={'verbose_name': 'Former Student', 'verbose_name_plural': 'Former Students'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
