# Generated by Django 4.0 on 2022-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0002_alter_applyingstudent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ApplyingStudent', 'ApplyingStudent'), ('FormerStudent', 'FormerStudent'), ('DepartmentCoordinator', 'DepartmentCoordinator'), ('Instructor', 'Instructor'), ('ExchangeCoordinator', 'ExchangeCoordinator'), ('ExchangeOffice', 'ExchangeOffice')], default='FormerStudent', max_length=30),
        ),
    ]
