# Generated by Django 4.0 on 2022-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeoffice',
            options={'verbose_name': 'Exchange Office Account', 'verbose_name_plural': 'Exchange Offices Accounts'},
        ),
    ]
