# Generated by Django 4.0 on 2022-12-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0004_alter_exchangeoffice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyingstudent',
            name='applied_university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_university', to='dbint.university'),
        ),
        migrations.AddField(
            model_name='applyingstudent',
            name='coordinator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_depc', to='dbint.departmentcoordinator'),
        ),
        migrations.AddField(
            model_name='applyingstudent',
            name='exc_coordinator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_excc', to='dbint.exchangecoordinator'),
        ),
    ]
