# Generated by Django 4.0 on 2022-12-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0005_applyingstudent_applied_university_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyingstudent',
            old_name='coordinator',
            new_name='stu_depc',
        ),
        migrations.RenameField(
            model_name='applyingstudent',
            old_name='exc_coordinator',
            new_name='stu_excc',
        ),
    ]
