# Generated by Django 4.0 on 2022-12-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0007_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcoordinator',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default='CS', max_length=10),
        ),
    ]
