# Generated by Django 4.0 on 2022-12-16 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0008_alter_departmentcoordinator_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='pdf', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, max_length=40)),
                ('documentOwner', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbint.user')),
            ],
        ),
        migrations.AddField(
            model_name='applyingstudent',
            name='universityPlaced',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbint.university'),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='availablePeriod',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='quotaPlacement',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PreApprovalFormContent',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbint.document')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Surname', models.CharField(default='', max_length=100)),
                ('IDNumber', models.IntegerField(default=0, max_length=15)),
                ('Department', models.CharField(default='', max_length=100)),
                ('hostInst', models.CharField(default='', max_length=100)),
                ('academicYear', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(default='', max_length=100)),
                ('coordinatorName', models.CharField(default='', max_length=100)),
            ],
            bases=('dbint.document',),
        ),
    ]
