# Generated by Django 4.0 on 2022-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0009_document_applyingstudent_universityplaced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapprovalformcontent',
            name='IDNumber',
            field=models.IntegerField(default=0),
        ),
    ]
