# Generated by Django 4.0 on 2022-12-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0010_alter_preapprovalformcontent_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyingstudent',
            name='universityPlaced',
        ),
    ]
