# Generated by Django 4.0 on 2022-12-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0011_remove_applyingstudent_universityplaced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeoffice',
            options={'verbose_name': 'Exchange Office Account', 'verbose_name_plural': 'Exchange Office Accounts'},
        ),
        migrations.AlterField(
            model_name='applyingstudent',
            name='check_list',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='astu_owner', to='dbint.todolist'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='instructor_of_course', to='dbint.Course'),
        ),
        migrations.AlterField(
            model_name='management',
            name='check_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_owner', to='dbint.todolist'),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(verbose_name='The task should be completed before this date')),
                ('list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dbint.todolist')),
            ],
        ),
    ]
