# Generated by Django 4.0 on 2022-12-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0012_alter_exchangeoffice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='reviewCount',
            new_name='review_count',
        ),
    ]
