# Generated by Django 4.0 on 2022-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0013_rename_reviewcount_university_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formerstudent',
            name='begin_date',
            field=models.DateField(default=None, max_length='20'),
        ),
        migrations.AlterField(
            model_name='formerstudent',
            name='end_date',
            field=models.DateField(auto_now_add=True, max_length='20'),
        ),
    ]
