# Generated by Django 4.0 on 2022-12-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0015_alter_formerstudent_begin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formerstudent',
            name='uni_visited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='former_students', to='dbint.universitydepartment'),
        ),
    ]
