# Generated by Django 4.0 on 2022-12-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0017_review_date_alter_review_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='dbint.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='dbint.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default='CS', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_link',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='formerstudent',
            name='entered_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='dbint.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dbint.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fstu_reviews', to='dbint.user'),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='availablePeriod',
            field=models.CharField(choices=[('FALL', 'FALL'), ('SPRING', 'SPRING'), ('YEAR', 'YEAR')], default='FALL', max_length=10),
        ),
        migrations.CreateModel(
            name='ForeignCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME')], default='CS', max_length=10)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('credits', models.FloatField(default=0)),
                ('syllabus_link', models.CharField(default='', max_length=300)),
                ('university', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_course_university', to='dbint.university')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_status', models.BooleanField(default=False)),
                ('bilkent_course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bilkent_course', to='dbint.course')),
                ('foreign_course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_course', to='dbint.foreigncourse')),
            ],
        ),
    ]
