# Generated by Django 4.0 on 2022-12-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0018_remove_chat_receiver_remove_chat_sender_chat_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fstu_reviews', to='dbint.formerstudent'),
        ),
    ]
