# Generated by Django 4.0 on 2022-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0019_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='media/profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
