# Generated by Django 4.0 on 2022-12-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0023_notification_type_alter_formerstudent_uni_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='universitydepartment',
            name='coordinator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_unis', to='dbint.departmentcoordinator'),
        ),
    ]
