# Generated by Django 4.0 on 2022-12-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0024_alter_student_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['receive_date']},
        ),
    ]
