# Generated by Django 4.0 on 2022-12-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0025_alter_document_options_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=None, upload_to='files'),
        ),
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(default='xlsx', max_length=10),
        ),
        migrations.AlterField(
            model_name='applyingstudent',
            name='stu_depc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='dbint.departmentcoordinator'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='Excel File', max_length=100),
        ),
    ]
