# Generated by Django 4.0 on 2022-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0027_remove_document_documentowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyingstudent',
            name='period',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listitem',
            name='type',
            field=models.CharField(default='Upload File', max_length=100),
        ),
    ]
