# Generated by Django 4.0 on 2022-12-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0030_notification_included_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-receive_date']},
        ),
    ]
