# Generated by Django 4.0 on 2022-12-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbint', '0031_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AlterField(
            model_name='courserelation',
            name='bilkent_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='dbint.course'),
        ),
        migrations.AlterField(
            model_name='courserelation',
            name='foreign_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_relation', to='dbint.foreigncourse'),
        ),
    ]
